routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/crud', function () {
    return view('crud');
});

Route::get('/users','HomeController@getUsers')->name('user.all');

Route::post('/save','HomeController@save')->name('user.save');

Route::get('/export','HomeController@export')->name('user.export');


Route::get('/user','HomeController@getUser')->name('user.get');

Route::post('/update','HomeController@update')->name('user.update');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['prefix'=>'company'],function()
{ 
    Route::get('delete/{id}','CompanyController@destroy')->name('company.delete');
    Route::post('update','CompanyController@update')->name('company.update');
    Route::get('import-data', 'ImportExcel\ImportExcelController@indexCompany')->name('company.import');
    Route::post('upload', 'ImportExcel\ImportExcelController@importCompany')->name('company.upload');
});

Route::group(['prefix'=>'employee'],function()
{ 
    Route::get('delete/{id}','EmployeeController@destroy')->name('employee.delete');
    Route::post('update','EmployeeController@update')->name('employee.update');
    Route::get('import', 'ImportExcel\ImportExcelController@indexEmployee')->name('employee.import');
    Route::post('upload-data', 'ImportExcel\ImportExcelController@importEmployee')->name('employee.upload');
});


Route::resource('company', 'CompanyController');
Route::resource('employee', 'EmployeeController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Employee;

class Company extends Model
{
    protected $fillable = ['uuid','cname','cemail','logo','website','status'];

    public static $rules = array(
        'cname'=>'required|min:2|max:20',
        'cemail'=>'required|email|unique:companies',
        'logo'=>'image|mimes:jpeg,png,jpg|max:2048',
        'website'=>'required',
        'status'=>'required');

    public function employee()
    {
        return $this->hasMany(Employee::class);
    }

    
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use App\Company;
use Illuminate\Support\Facades\Crypt;
use Validator;
use Webpatser\Uuid\Uuid;


class CompanyController extends Controller
{
    protected $paginate =10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::orderBy('id','desc')->withCount('employee')->paginate($this->paginate);
        return view('company.list',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      //  dd(request()->all());
        $validator = Validator::make(request()->all(), Company::$rules);
        if ($validator->fails()) {
            return back()->withErrors($validator->errors())->withInput();
        }
        $imageName = time().'.'.request('logo')->extension();  
        $data =  request()->except('_token');
        $data['logo'] = $imageName;
        $data['uuid'] = Uuid::generate();
        $company = Company::create($data); 
        if($company)
        {
            request('logo')->move(public_path('logo'), $imageName);
            return redirect()->to('company')->with('success', 'Company created successfully.');
        } 
        else
        {
            return redirect()->back()->with('warning', 'Company not created.');    
        } 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
      
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::where('uuid',$id)->first();
        $company->logo = env('ASSETS_URL').$company->logo;
        return view('company.edit',compact('company'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $id = request('id');
        $company = Company::where('uuid',$id)->first();
        if(!$company)
           return redirect()->back()->with('warning', 'Company details not found.');       

        $validator = Validator::make(request()->all(), ['cname'=>'required|min:2|max:20',
        'cemail'=>'required|email|unique:companies,cemail,'.$company->id,'logo'=>'image|mimes:jpeg,png,jpg|max:2048',
        'website'=>'required','status'=>'required']);

        if ($validator->fails()) {
            return back()->withErrors($validator->errors())->withInput();
        }

        $data =  request()->except(['_token','id']);
        if(request('logo')){
            $imageName = time().'.'.request('logo')->extension();  
            $data['logo'] = $imageName;
            request('logo')->move(public_path('logo'), $imageName);
        }
        $update = $company->fill($data)->save();
        if($update)
            return redirect()->to('company')->with('success', 'Company details updated successfully.');
        else
            return redirect()->back()->with('warning', 'Company details not updated.');       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::where('uuid',$id)->delete();
        if(!$company)
            return redirect()->back()->with('warning', 'Company details not found.'); 
        return redirect()->back()->with('success', 'Company deleted successfully.');
    }

}   

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Company
                <a href="{{url('company')}}" style="margin-left:60%;"> Company List</a></div>
                <div class="card-body">
        <form class="form-horizontal" method="post" action="{{url('company')}}" id="company-form" enctype="multipart/form-data">
            <h3 style="text-align:center;">Enter Company Details </h3>
              <div class="col-md-10" style="margin-top:20px;">
                 <div class="form-group">
                    <label class="control-label col-sm-4" for="name">Name:</label>
                    <div class="col-sm-8">
                       <input type="text" class="form-control" id="name" placeholder="Enter Name" required name="cname" value="{{old('cname')}}">
                    </div>
                 </div>
                 <div class="form-group">
                    <label class="control-label col-sm-4" for="email">Email:</label>
                    <div class="col-sm-8">
                       <input type="email" class="form-control" id="email" placeholder="Email" required name="cemail" value="{{old('cemail')}}">
                    </div>
                 </div>
                 <div class="form-group">
                    <label class="control-label col-sm-4" for="logo">Logo:</label>
                    <div class="col-sm-8">
                       <input type="file"  id="logo"  required name="logo" accept="image/png, image/gif, image/jpeg">
                    </div>
                 </div>
              </div>
              <div class="col-md-10">
                 <div class="form-group">
                    <label class="control-label col-sm-4" for="website">Website:</label>
                    <div class="col-sm-8">
                       <input type="url" class="form-control" id="website" placeholder="Enter Website" required name="website" value="{{old('website')}}">
                    </div>
                 </div>

                 <div class="form-group">
                    <label class="control-label col-sm-4" for="email">Status:</label>
                    <div class="col-sm-8">
                       <input type="radio" name="status" required value="active" checked>Active
                       <input type="radio" name="status" required value="inactive">Inactive
                    </div>
                 </div>
              </div>
            <div class="row">
               <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-8">
                     <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
               </div>
               @csrf
             </div>
           </form>
<!-- Tabs content -->
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
         
         
         $(document).ready(function()
         {   
      //   loadData();
         });
         
         function loadData()
         {   
         $.ajax({
             type:"get",
             url:"{{url('company')}}",
             success:function(res){
                 $('#data').html(res);
             }
         });
         return false;
         }
         
         $(function () { //import-form
         $('#company-form').parsley().on('field:validated', function() {
         var ok = $('.parsley-error').length === 0;
         $('.bs-callout-info').toggleClass('hidden', !ok);
         $('.bs-callout-warning').toggleClass('hidden', ok);
         })
         .on('form:submit', function() {
             return true;
         });

        //  $('#import-form').parsley().on('field:validated', function() {
        //  var ok = $('.parsley-error').length === 0;
        //  $('.bs-callout-info').toggleClass('hidden', !ok);
        //  $('.bs-callout-warning').toggleClass('hidden', ok);
        //  })
        //  .on('form:submit', function() {
        //    return true;
        //  });
         });
      </script>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Company
                <a href="{{url('company')}}" style="margin-left:60%;"> Company List</a></div>
                <div class="card-body">
        <form class="form-horizontal" method="post" action="{{url('company/update')}}" id="company-form" enctype="multipart/form-data">
            <h3 style="text-align:center;">Enter Company Details </h3>
            <div class="col-md-12">
                        <div class="form-group">
                           <label class="control-label col-sm-4" for="name">Name:</label>
                           <div class="col-sm-8">
                              <input type="text" class="form-control name" placeholder="Enter Name" required name="cname" value="{{old('cname',$company->cname)}}">
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="control-label col-sm-4" for="email">Email:</label>
                           <div class="col-sm-8">
                              <input type="email" class="form-control email" placeholder="Email" required name="cemail" value="{{old('cname',$company->cemail)}}">
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="control-label col-sm-4" for="logo">Logo:</label>
                           <div class="col-sm-8">
                              <input type="file" class="form-control logo"  name="logo" id="imgInp" >
                              <img src="{{$company->logo}}" id="logo" style="width:100px;height:100px;" />
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="control-label col-sm-4" for="website">Website:</label>
                           <div class="col-sm-8">
                              <input type="url" class="form-control website" placeholder="Enter Website" required name="website"  value="{{old('website',$company->website)}}">
                           </div>
                        </div>
                        <div class="form-group">
                           <label class="control-label col-sm-4" for="pincode">Status:</label>
                           <div class="col-sm-8">
                              <input type="radio" name="status" id="active" @if($company->status=='active') checked @endif value="active">Active
                              <input type="radio" name="status"  id="inactive"  @if($company->status=='inactive') checked @endif value="inactive">Inactive
                           </div>
                        </div>
                     </div>
                  <div class="row">
                     <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                           @csrf
                           <input type="hidden" name="id" value="{{$company->uuid}}">
                           <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                     </div>
                  </div>
           </form>
<!-- Tabs content -->
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
         
         function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#logo').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp").change(function(){
    readURL(this);
});
        
         
         $(function () { //import-form
         $('#company-form').parsley().on('field:validated', function() {
         var ok = $('.parsley-error').length === 0;
         $('.bs-callout-info').toggleClass('hidden', !ok);
         $('.bs-callout-warning').toggleClass('hidden', ok);
         })
         .on('form:submit', function() {
             return true;
         });
       
         });
      </script>
@endsection

resources/views/company/import.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Upload Company
                <a href="{{url('company/create')}}" style="margin-left:60%;"> + Create Company</a>/
                <a href="{{url('company')}}"> Company List</a></div>
                

<!-- Tabs content -->
        <h3 style="text-align:center";>Upload CSV file</h3>
         <div class="col-md-6">
         <div class="form-group">
         <form action="{{ route('company.upload') }}" method="POST" id="import-form" name="importform" enctype="multipart/form-data">
         @csrf
         <input type="file" name="import_file" class="form-control" required accept=".csv">
         <button type="submit" class="btn btn-success" style="margin-top:20px;">Import File</button>
         </form>
         </div>
         <div class="col-md-6">
          <h4>Sample File : </h4>Sample file  <a href="{{asset('company.csv')}}">Click here</a>
         </div>
         </div>
         <hr>

            
<!-- Tabs content -->

                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(function () { //import-form
$('#import-form').parsley().on('field:validated', function() {
         var ok = $('.parsley-error').length === 0;
         $('.bs-callout-info').toggleClass('hidden', !ok);
         $('.bs-callout-warning').toggleClass('hidden', ok);
         })
         .on('form:submit', function() {
           return true;
         });
        });        
</script>
@endsection

resources/views/company/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Company List
                <a href="{{url('company/create')}}" style="margin-left:60%;"> + Create Company</a>/
                <a href="{{route('company.import')}}"> Bulk upload</a></div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                  

<!-- Tabs content -->
        <table id="myTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
               <tr>
                  <th>#S.No</th>
                  <th>Company Name</th>
                  <th>Email</th>
                  <th>Logo</th>
                  <th>Website</th>
                  <th>Total Employee</th>
                  <th>Status</th>
                  <th>Action</th>
               </tr>
            </thead>
              <tbody id="data">
              @foreach($companies as $company)
            <tr>
                <td>#{{$company->id}}</td>
                <td>{{$company->cname}}</td>
                <td>{{$company->cemail}}</td>
                <td><img src="{{asset('logo/'.$company->logo)}}" style="width:100px;height:100px;" ></td>
                <td>{{$company->website}}</td>
                <td>{{$company->employee_count}}</td>
                <td>{{ucfirst($company->status)}}</td>
                <td> <a  href="{{route('company.edit', $company->uuid)}}">Edit</a>
                  / <a href="{{url('company/delete',$company->uuid)}}">Delete</a></td>
            </tr>
  @endforeach     

              </tbody>
         </table>
<!-- Tabs content -->
{{ $companies->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
<script>

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#logo').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp").change(function(){
    readURL(this);
});


function edit(id) {
           $.ajax({
             type : 'get',
             url  : url,
             data : {'id':id},
             success:function(data){
               console.log(data);
               $('.id').val(data.id);
               $('.name').val(data.cname);
               $('.email').val(data.cemail);
               $('.website').val(data.website);
               if(data.status == 'active')
                   $("#active").prop("checked", true);
               else
                   $("#inactive").prop("checked", true);
               $('#logo').attr('src',data.logo);
               $('#exampleModal').modal();
             }
           });
         }

         $(function () { //import-form
         $('#edit-form').parsley().on('field:validated', function() {
         var ok = $('.parsley-error').length === 0;
         $('.bs-callout-info').toggleClass('hidden', !ok);
         $('.bs-callout-warning').toggleClass('hidden', ok);
         })
         .on('form:submit', function() {
             return true;
         });     
         });
</script>
@endsection